name: Run on Push to Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a script or build process
        run: |
          echo "This is where you can run your build or test scripts."
          # Add your custom commands here
